services:
  - type: web
    name: django-ecommerce-api
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PIP_VERSION
        value: 23.3.1
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.development
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"