# Generated by Django 4.0.4 on 2025-07-03 19:58

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=products.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.ImageField(upload_to=products.models.category_image_path),
        ),
    ]
