# Generated by Django 4.0.4 on 2025-07-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_cartitem'),
    ]

    operations = [
    ]
